version: '2.0'
services:
  updater:
    build: .
    environment: 
        - DOWNLOAD_LINK_CONFIRMED=https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv
        - DOWNLOAD_LINK_DEATHS=https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv
        - DOWNLOAD_LINK_RECOVERED=https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv
        - COUNTRY_STRING=Germany
        - COUNTRY_COLUMN=1
        - FIRST_DATE_COLUMN=4
        - INFLUXDB_HOST=
        - INFLUXDB_PORT=8086
        - INFLUXDB_DBNAME=covid_19
        - INFLUXDB_USER=admin
        - INFLUXDB_USER_PASSWORD=
